version: '3'

volumes:
  db_mysql_dev:

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_mysql_dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password_development

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
